name = "dap"
version = "0.1.0"
defaultTargets = ["dap", "toydap", "dap-tests"]

[[lean_lib]]
name = "Dap"

[[lean_lib]]
name = "examples"

[[lean_exe]]
name = "dap"
root = "Main"

[[lean_exe]]
name = "toydap"
root = "ToyDap"
supportInterpreter = true

[[lean_exe]]
name = "dap-export"
root = "ExportMain"
supportInterpreter = true

[[lean_exe]]
name = "dap-tests"
root = "Test.Main"
