name = "implab"
version = "0.1.0"
defaultTargets = ["toydap", "dap-tests"]

[[lean_lib]]
name = "ImpLab"

[[lean_lib]]
name = "examples"

[[lean_lib]]
name = "Test"

[[lean_exe]]
name = "toydap"
root = "app.ToyDap"
supportInterpreter = true

[[lean_exe]]
name = "dap-export"
root = "app.ExportMain"
supportInterpreter = true

[[lean_exe]]
name = "dap-tests"
root = "Test.Main"
